//! Wi-Fi setup mode: an open `Radix-Setup` hotspot with a captive portal where you pick the
//! network the clock should join. The choice is saved to flash and the board restarts.
//!
//! Pieces: the hotspot + scanning ([`wifi_task`]), a DHCP server that hands phones an address
//! and the portal URL ([`dhcp_task`]), a DNS server that points every name at us ([`dns_task`]),
//! and the web page itself ([`http_task`]).

mod dns;
pub mod page;

use alloc::{format, vec::Vec};
use core::{
    cell::{Cell, RefCell},
    net::{Ipv4Addr, SocketAddr, SocketAddrV4},
    sync::atomic::{AtomicU32, Ordering},
};

use critical_section::Mutex;
use edge_dhcp::{
    io::DEFAULT_SERVER_PORT,
    server::{Server, ServerOptions},
};
use edge_nal::UdpBind;
use edge_nal_embassy::{Udp, UdpBuffers};
use embassy_futures::select::{Either3, select3};
use embassy_net::{
    Ipv4Cidr, Stack, StaticConfigV4,
    tcp::TcpSocket,
    udp::{PacketMetadata, UdpSocket},
};
use embassy_sync::{blocking_mutex::raw::CriticalSectionRawMutex, signal::Signal};
use embassy_time::{Duration, Instant, Timer};
use embedded_io_async::Write as _;
use esp_radio::wifi::{
    AuthenticationMethod, AuthenticationMethodConfig, Config, WifiController,
    ap::AccessPointConfig,
    scan::{ScanConfig, ScanTypeConfig},
    sta::StationConfig,
};
use esp_storage::FlashStorage;

use crate::{credentials::Credentials, storage};
use page::Network;

pub const AP_SSID: &str = "Radix-Setup";
pub const AP_IP: Ipv4Addr = Ipv4Addr::new(192, 168, 4, 1);
const PORTAL_URL: &str = "http://192.168.4.1/";

/// Listen this long per channel. The library default (10-20 ms) is too short while the radio
/// also serves the hotspot, and behind the metal case: it often found nothing at all.
const SCAN_TYPE: ScanTypeConfig = ScanTypeConfig::Active {
    min: esp_hal::time::Duration::from_millis(60),
    max: esp_hal::time::Duration::from_millis(150),
};
/// Scans per round, merged: each one can miss a network that another catches.
const SCAN_PASSES: usize = 2;
/// While no network has been found, scan again this often.
const EMPTY_RESCAN_EVERY: Duration = Duration::from_secs(5);

/// Order of the glyphs in `ui/font/text.slint` (generated by `tools/gen_sprites.py`).
const TEXT_CHARS: &str = " ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-.:!?/";

/// Glyph indices for the pixel text font; lowercase is shown as uppercase, anything else as `?`.
pub fn glyphs(text: &str) -> Vec<i32> {
    let unknown = TEXT_CHARS.find('?').unwrap_or(0) as i32;
    text.chars()
        .map(|c| {
            TEXT_CHARS
                .find(c.to_ascii_uppercase())
                .map_or(unknown, |i| i as i32)
        })
        .collect()
}

/// Hotspot for phones to join, plus an idle station so we can scan for networks.
pub fn wifi_config() -> Config {
    Config::AccessPointStation(
        StationConfig::default(),
        AccessPointConfig::default()
            .with_ssid(AP_SSID.try_into().unwrap())
            .with_authentication(AuthenticationMethodConfig::Open),
    )
}

pub fn net_config() -> embassy_net::Config {
    embassy_net::Config::ipv4_static(StaticConfigV4 {
        address: Ipv4Cidr::new(AP_IP, 24),
        gateway: Some(AP_IP),
        dns_servers: Default::default(),
    })
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum State {
    Waiting,
    /// New credentials are in flash; the board should restart.
    Saved,
}

static STATE: Mutex<Cell<State>> = Mutex::new(Cell::new(State::Waiting));
static NETWORKS: Mutex<RefCell<Vec<Network>>> = Mutex::new(RefCell::new(Vec::new()));
static FLASH: Mutex<RefCell<Option<FlashStorage<'static>>>> = Mutex::new(RefCell::new(None));
static RESCAN: Signal<CriticalSectionRawMutex, ()> = Signal::new();
static SCANS_DONE: AtomicU32 = AtomicU32::new(0);
/// Shown at the top of the page, e.g. why the saved network couldn't be joined.
static NOTICE: Mutex<Cell<Option<&'static str>>> = Mutex::new(Cell::new(None));

pub fn state() -> State {
    critical_section::with(|cs| STATE.borrow(cs).get())
}

/// Hands the flash to the web page so it can save what the user picks.
pub fn give_flash(flash: FlashStorage<'static>) {
    critical_section::with(|cs| *FLASH.borrow_ref_mut(cs) = Some(flash));
}

/// A message for the top of the setup page.
pub fn set_notice(message: &'static str) {
    critical_section::with(|cs| NOTICE.borrow(cs).set(Some(message)));
}

fn notice() -> Option<&'static str> {
    critical_section::with(|cs| NOTICE.borrow(cs).get())
}

fn networks() -> Vec<Network> {
    critical_section::with(|cs| NETWORKS.borrow_ref(cs).clone())
}

/// Scans at start, on request, and every few seconds until something is found; keeps the
/// hotspot running.
#[embassy_executor::task]
pub async fn wifi_task(mut controller: WifiController<'static>) {
    log::info!("setup hotspot {AP_SSID:?} up, portal at {PORTAL_URL}");
    loop {
        scan(&mut controller).await;
        let retry_at = if networks().is_empty() {
            Instant::now() + EMPTY_RESCAN_EVERY
        } else {
            Instant::MAX
        };
        loop {
            let event = select3(
                RESCAN.wait(),
                Timer::at(retry_at),
                controller.wait_for_access_point_connected_event_async(),
            )
            .await;
            match event {
                Either3::First(()) | Either3::Second(()) => break,
                Either3::Third(Ok(event)) => log::info!("setup hotspot: {event:?}"),
                Either3::Third(Err(e)) => {
                    log::warn!("setup hotspot event error: {e:?}");
                    Timer::after(Duration::from_secs(1)).await;
                }
            }
        }
    }
}

/// A few scan passes, merged. An empty round keeps the list we already had.
async fn scan(controller: &mut WifiController<'static>) {
    let config = ScanConfig::default().with_scan_type(SCAN_TYPE).with_max(32);
    let mut found = Vec::new();
    for _ in 0..SCAN_PASSES {
        match controller.scan_async(&config).await {
            Ok(aps) => found.extend(aps.iter().map(|ap| Network {
                ssid: ap.ssid.as_str().into(),
                rssi: ap.signal_strength,
                open: matches!(ap.auth_method, None | Some(AuthenticationMethod::None)),
            })),
            Err(e) => log::warn!("wifi scan failed: {e:?}"),
        }
    }
    let networks = page::tidy_networks(found);
    log::info!("scan found {} networks", networks.len());
    if !networks.is_empty() {
        critical_section::with(|cs| *NETWORKS.borrow_ref_mut(cs) = networks);
    }
    SCANS_DONE.fetch_add(1, Ordering::Relaxed);
}

/// Gives phones an address, us as their DNS server, and the portal URL (RFC 8910),
/// which newer phones use to open the setup page straight away.
#[embassy_executor::task]
pub async fn dhcp_task(stack: Stack<'static>) {
    let buffers = UdpBuffers::<1>::new();
    let udp = Udp::new(stack, &buffers);
    let bind_to = SocketAddr::V4(SocketAddrV4::new(
        Ipv4Addr::UNSPECIFIED,
        DEFAULT_SERVER_PORT,
    ));
    let mut socket = match udp.bind(bind_to).await {
        Ok(socket) => socket,
        Err(e) => {
            log::error!("dhcp bind failed: {e:?}");
            return;
        }
    };

    let dns_servers = [AP_IP];
    let mut gateway = [Ipv4Addr::UNSPECIFIED];
    let mut options = ServerOptions::new(AP_IP, Some(&mut gateway));
    options.dns = &dns_servers;
    options.captive_url = Some(PORTAL_URL);
    let mut server: Server<_, 8> = Server::new(|| Instant::now().as_secs(), AP_IP);
    let mut buffer = [0u8; 1500];

    loop {
        if let Err(e) =
            edge_dhcp::io::server::run(&mut server, &options, &mut socket, &mut buffer).await
        {
            log::warn!("dhcp server: {e:?}");
            Timer::after(Duration::from_secs(1)).await;
        }
    }
}

/// Answers every DNS lookup with our own address.
#[embassy_executor::task]
pub async fn dns_task(stack: Stack<'static>) {
    let mut rx_meta = [PacketMetadata::EMPTY; 4];
    let mut rx_buffer = [0u8; 1024];
    let mut tx_meta = [PacketMetadata::EMPTY; 4];
    let mut tx_buffer = [0u8; 1024];
    let mut socket = UdpSocket::new(
        stack,
        &mut rx_meta,
        &mut rx_buffer,
        &mut tx_meta,
        &mut tx_buffer,
    );
    if let Err(e) = socket.bind(53) {
        log::error!("dns bind failed: {e:?}");
        return;
    }

    let mut query = [0u8; 512];
    let mut reply = [0u8; 512];
    loop {
        let Ok((len, from)) = socket.recv_from(&mut query).await else {
            continue;
        };
        if let Some(reply_len) = dns::answer(&query[..len], AP_IP.octets(), &mut reply) {
            let _ = socket.send_to(&reply[..reply_len], from).await;
        }
    }
}

/// Serves the setup page. Two run at once, since phones fire several requests on joining.
#[embassy_executor::task(pool_size = 2)]
pub async fn http_task(stack: Stack<'static>) {
    let mut rx_buffer = [0u8; 1536];
    let mut tx_buffer = [0u8; 2048];
    loop {
        let mut socket = TcpSocket::new(stack, &mut rx_buffer, &mut tx_buffer);
        socket.set_timeout(Some(Duration::from_secs(10)));
        if socket.accept(80).await.is_err() {
            continue;
        }
        if let Err(e) = handle(&mut socket).await {
            log::debug!("http: {e}");
        }
        let _ = socket.flush().await;
        socket.close();
        Timer::after(Duration::from_millis(500)).await;
        socket.abort();
    }
}

async fn handle(socket: &mut TcpSocket<'_>) -> Result<(), &'static str> {
    let mut buffer = [0u8; 2048];
    let mut len = 0;
    let header_end = loop {
        if let Some(i) = buffer[..len].windows(4).position(|w| w == b"\r\n\r\n") {
            break i + 4;
        }
        if len == buffer.len() {
            return Err("headers too large");
        }
        match socket.read(&mut buffer[len..]).await {
            Ok(0) | Err(_) => return Err("connection closed"),
            Ok(n) => len += n,
        }
    };

    let (head, rest) = buffer.split_at_mut(header_end);
    let head = core::str::from_utf8(head).map_err(|_| "bad headers")?;
    let mut request = head.split("\r\n").next().unwrap_or("").split(' ');
    let method = request.next().unwrap_or("");
    let path = request
        .next()
        .unwrap_or("/")
        .split('?')
        .next()
        .unwrap_or("/");
    let content_length = head
        .split("\r\n")
        .filter_map(|line| line.split_once(':'))
        .find(|(name, _)| name.trim().eq_ignore_ascii_case("content-length"))
        .and_then(|(_, value)| value.trim().parse::<usize>().ok())
        .unwrap_or(0);

    if content_length > rest.len() {
        return respond(socket, "413 Payload Too Large", "", b"").await;
    }
    let mut body_len = len - header_end;
    while body_len < content_length {
        match socket.read(&mut rest[body_len..content_length]).await {
            Ok(0) | Err(_) => return Err("connection closed"),
            Ok(n) => body_len += n,
        }
    }
    let body = core::str::from_utf8(&rest[..content_length]).unwrap_or("");

    match (method, path) {
        ("POST", "/save") => save(socket, body).await,
        ("POST", "/rescan") => {
            rescan().await;
            redirect(socket, "303 See Other", "/").await
        }
        ("GET", "/") => html(socket, &page::setup_page(&networks(), notice())).await,
        _ => match asset(path) {
            Some((content_type, bytes)) if method == "GET" => {
                let headers =
                    format!("Content-Type: {content_type}\r\nCache-Control: max-age=86400\r\n");
                respond(socket, "200 OK", &headers, bytes).await
            }
            // Phones probe URLs like /generate_204 or /hotspot-detect.html to detect captive
            // portals; sending those (and anything else) to the page is what triggers the popup.
            _ => redirect(socket, "302 Found", PORTAL_URL).await,
        },
    }
}

async fn save(socket: &mut TcpSocket<'_>, body: &str) -> Result<(), &'static str> {
    let typed = page::form_field(body, "other").unwrap_or_default();
    let ssid = if typed.trim().is_empty() {
        page::form_field(body, "ssid").unwrap_or_default()
    } else {
        typed.trim().into()
    };
    let password = page::form_field(body, "password").unwrap_or_default();

    let credentials = match Credentials::new(&ssid, &password) {
        Ok(credentials) => credentials,
        Err(message) => return html(socket, &page::setup_page(&networks(), Some(message))).await,
    };

    let Some(mut flash) = critical_section::with(|cs| FLASH.borrow_ref_mut(cs).take()) else {
        let busy = "Still saving the last attempt - try again in a moment.";
        return html(socket, &page::setup_page(&networks(), Some(busy))).await;
    };
    let saved = storage::save(&mut flash, &credentials);
    give_flash(flash);

    match saved {
        Ok(()) => {
            log::info!("saved wifi network {:?}", credentials.ssid);
            let sent = html(socket, &page::saved_page(&credentials.ssid)).await;
            critical_section::with(|cs| STATE.borrow(cs).set(State::Saved));
            sent
        }
        Err(e) => {
            log::error!("saving wifi credentials failed: {e}");
            let failed = "Couldn't save to flash. Please try again.";
            html(socket, &page::setup_page(&networks(), Some(failed))).await
        }
    }
}

/// Asks [`wifi_task`] for a fresh scan and waits (a few seconds at most) for it to finish.
async fn rescan() {
    let before = SCANS_DONE.load(Ordering::Relaxed);
    RESCAN.signal(());
    let deadline = Instant::now() + Duration::from_secs(12);
    while SCANS_DONE.load(Ordering::Relaxed) == before && Instant::now() < deadline {
        Timer::after(Duration::from_millis(200)).await;
    }
}

/// The page's font and sun, built into the firmware by `tools/gen_sprites.py`.
fn asset(path: &str) -> Option<(&'static str, &'static [u8])> {
    const PNG: &str = "image/png";
    Some(match path {
        "/pixel.ttf" => ("font/ttf", include_bytes!("../../ui/web/pixel.ttf")),
        "/sun.png" => (PNG, include_bytes!("../../ui/weather/clear_day.png")),
        _ => return None,
    })
}

async fn html(socket: &mut TcpSocket<'_>, page: &str) -> Result<(), &'static str> {
    let headers = "Content-Type: text/html; charset=utf-8\r\nCache-Control: no-store\r\n";
    respond(socket, "200 OK", headers, page.as_bytes()).await
}

async fn redirect(
    socket: &mut TcpSocket<'_>,
    status: &str,
    location: &str,
) -> Result<(), &'static str> {
    let headers = format!("Location: {location}\r\nCache-Control: no-store\r\n");
    respond(socket, status, &headers, b"").await
}

async fn respond(
    socket: &mut TcpSocket<'_>,
    status: &str,
    headers: &str,
    body: &[u8],
) -> Result<(), &'static str> {
    let head = format!(
        "HTTP/1.1 {status}\r\n{headers}Content-Length: {}\r\nConnection: close\r\n\r\n",
        body.len()
    );
    socket
        .write_all(head.as_bytes())
        .await
        .map_err(|_| "write failed")?;
    socket.write_all(body).await.map_err(|_| "write failed")
}
